backend:
#  name: git-gateway
  name: test-repo
#  branch: netlifycms
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/images
public_folder: /images

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    extension: mdx
    widget: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Publish Date", name: "created", widget: "datetime"}
      - {label: "Updated Date", name: "updated", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: image}
      - {label: "Body", name: "body", widget: "mdx"}
      - {label: "Categories", name: "categories", widget: "list"}
