backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/images
public_folder: /images

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    extension: mdx
    widget: mdx
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: post }
      - { label: Title, name: title, widget: string }
      - { label: Slug start with "/", name: slug, widget: string, required: false }
      - { label: Heading, name: heading, widget: string }
      - { label: Draft, name: draft, widget: boolean }
      - { label: Show Sidebar, name: showSidebar, widget: boolean, default: true }
      - { label: Publish Date, name: created, widget: datetime }
      - { label: Updated Date, name: updated, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Featured Image, name: featuredImage, widget: image }
      - { label: Body, name: body, widget: mdx }
      - { label: Categories, name: categories, widget: list }
    view_filters:
      - label: Drafts
        field: draft
        pattern: true

  - name: page
    label: Page
    folder: content/pages
    create: true
    extension: mdx
    widget: mdx
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: post }
      - { label: Title, name: title, widget: string }
      - { label: Slug start with "/", name: slug, widget: string, required: false }
      - { label: Heading, name: heading, widget: string }
      - { label: Draft, name: draft, widget: boolean }
      - { label: Show Sidebar, name: showSidebar, widget: boolean, default: true }
      - { label: Description, name: description, widget: text }
      - { label: Body, name: body, widget: mdx }
    view_filters:
      - label: Drafts
        field: draft
        pattern: true

  - name: configs
    label: Configs
    editor:
      preview: false
    files:
      - file: content/configs/site-config.json
        label: Site Config
        name: site_config
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Description, name: siteDescription, widget: string }
          - { label: Site Url, name: siteUrl, widget: string }
          - { label: Site Language, name: siteLanguage, widget: string }
          - { label: Author, name: siteAuthor, widget: string }
          - { label: On/Off Site search, name: siteSearch, widget: boolean }
          - { label: Show Sidebar, name: siteShowSidebar, widget: boolean, default: true }
          - { label: Posts per page, name: sitePostsPerPage, widget: number, valueType: int, min: 5, max: 50, default: 5 }
          - { label: Categories, name: siteCategories, widget: list,
              fields:
                [
                { label: Name, name: name, widget: string },
                { label: Description, name: description, widget: markdown },
                ]
          }
          - { label: Social Links, name: siteSocialLinks, widget: list,
              fields:
                [
                { label: Name, name: name, widget: string },
                { label: URL, name: url, widget: string },
                ]
          }
          - { label: Top Menu, name: siteTopMenu, widget: list,
              fields:
                [
                { label: Text, name: text, widget: string },
                { label: URL, name: url, widget: string },
                ]
          }
          - { label: Footer Menu, name: siteFooterMenu, widget: list,
              fields:
                [
                { label: Text, name: text, widget: string },
                { label: URL, name: url, widget: string },
                ]
          }
          - { label: Site colors, name: siteColors, widget: object,
              fields:
                [
                { label: Background, name: backgroundColor, widget: color },
                { label: Primary, name: primaryColor, widget: color },
                { label: Primary Lighter, name: primaryColorLighter, widget: color },
                { label: Primary Darker, name: primaryColorDarker, widget: color },
                { label: Link Hover, name: linkColorHover, widget: color },
                { label: Dark, name: darkColor, widget: color },
                { label: Light Grey, name: lightGrey, widget: color },
                ]
          }
          - { label: Breakpoints, name: siteBreakpoints, widget: object,
              fields:
                [
                { label: XS, name: xs, widget: string },
                { label: SM, name: sm, widget: string },
                { label: MD, name: md, widget: string },
                { label: LG, name: lg, widget: string },
                { label: XL, name: xl, widget: string },
                ]
          }
          - { label: Fonts, name: siteFonts, widget: object,
              fields:
                [
                { label: Base, name: base, widget: string },
                { label: Heading, name: heading, widget: string },
                ]
          }
          - { label: Components, name: siteComponents, widget: object,
              fields:
                [
                { label: Container Width, name: containerWidth, widget: string },
                { label: Logo Width, name: logoWidth, widget: string },
                ]
          }
